apiVersion: v1
kind: Service
metadata:
  name: annotator-backend
  labels:
    {{- include "annotator-backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "annotator-backend.selectorLabels" . | nindent 4 }}
    app: annotator-backend
