---
# THIS IS NOT A TEMPLATE.
# This is just for linting the gha-workflows repo itself.
# We call the reusable workflow from its file path.
name: Docker Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.github/linters/**'

jobs:
  call-docker-build:

    name: Call Docker Build

    uses: ./.github/workflows/reusable-docker-build.yaml

    permissions:
      contents: read
      packages: write
      pull-requests: write

    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

    with:
      dockerhub-enable: true
      ghcr-enable: true
      platforms: linux/amd64,linux/arm64

      image-names: |
        kamikazer/${{ github.event.repository.name }}
        ghcr.io/${{ github.repository }}
